@host=http://127.0.0.1:8000
@username=new_user
@email=new@user.com
@password=new_user_password
@token=9f7e43a962971d7c9e77a0a500215390d02f8046
@question_slug=why-are-we-still-here-CZMejmOj


### Create new account
POST {{host}}/auth/users/
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "re_password": "{{password}}"
}


### Login
POST {{host}}/auth/token/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}


### Logout
POST {{host}}/auth/token/logout/
Authorization: token {{token}}


### Get question list
GET {{host}}/api/v1/questions/
Authorization: token {{token}}


### Create new question
POST {{host}}/api/v1/questions/
Content-Type: application/json
Authorization: token {{token}}

{
    "content": "Why are we still here?"
}


### View question
GET {{host}}/api/v1/questions/{{question_slug}}/
Authorization: token {{token}}


### TODO expand endpoint tests here